version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: buy-togheter-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: buy_togheter_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
